#!/bin/bash
#PBS -l nodes=1:ppn=8,walltime=48:00:00
#PBS -l vmem=30gb
#PBS -N cpac

# parse config.json for input parameters
PRECONFIG=$(jq -r .preconfig config.json)
if [ "$PRECONFIG" == "" ] || [ "$PRECONFIG" == "null" ] || [ "$PRECONFIG" == "default" ]
then
  PRECONFIG=""
else
  PRECONFIG="--preconfig $PRECONFIG"
fi
SAVE_WORKING_DIR=$(jq -r .saveWorkingDir config.json)
if [[ ${SAVE_WORKING_DIR} == 'true' ]]
then
  SAVE_WORKING_DIR=' --save_working_dir'
else
  SAVE_WORKING_DIR=''
fi

# get latest image if we don't already have one
if [ -f cpac-singularity-image.simg ]
then
  echo "using existing C-PAC Singularity image"
else
  echo "getting C-PAC Singularity image"
  time singularity pull cpac-singularity-image.simg shub://FCP-INDI/C-PAC || singularity pull cpac-singularity-image.simg docker://fcpindi/c-pac:latest
fi

# convert brainlife structure to BIDS
if [ ! -d bids ]
then
  echo "restructuring data"
  bl2bids
fi

set -x
set -e

# run C-PAC
echo "running C-PAC"
mkdir -p output tmp

time singularity run -e -B $PWD/bids:/bids -B $PWD/output:/output -B $PWD/tmp:/tmp cpac-singularity-image.simg /bids /output participant ${PRECONFIG}${SAVE_WORKING_DIR}
